Lesson 6
EvgeniyTsarkov/FreeIT-Java pull request #10
Opened 2021-03-28 18:10 UTC by EvgeniyTsarkov

The following tasks have been added:
Main Task 28
Alternative Task: Annotations Task
Please Check!

2021-03-29 17:01 UTC, michaelkotor requested changes

2021-03-29 17:01 UTC, michaelkotor commented on src/lesson_6/annotationstasks/Runner.java
> +        new VersionAnnotationProcessor().process(MyService.class);
So, main should contain something like `NameOfApplication.run()`

2021-03-29 17:01 UTC, michaelkotor commented on src/lesson_6/maintasks/Task28.java
> +class PolymorphArray<T> {
to extend, you may make a interface and implement this like List and ArrayList

2021-03-30 06:48 UTC, EvgeniyTsarkov commented on src/lesson_6/maintasks/Task28.java
> +class PolymorphArray<T> {
Done! refactored and tested.

2021-03-30 06:49 UTC, EvgeniyTsarkov commented on src/lesson_6/annotationstasks/Runner.java
> +        new VersionAnnotationProcessor().process(MyService.class);
Something's done... not sure exactly if it was what you've asked for. At least, I suggeested some kind of a solution. To the best of my un derstanding.

2021-04-01 13:29 UTC, michaelkotor approved these changes

2021-04-01 13:29 UTC, michaelkotor commented on src/lesson_6/annotationstasks/Runner.java
> +        new VersionAnnotationProcessor().process(MyService.class);
Good job!

2021-04-01 13:48 UTC, merged