Lesson 2
EvgeniyTsarkov/FreeIT-Java pull request #6
Opened 2021-02-26 12:36 UTC by EvgGit82

Lesson 2. Please check!

2021-03-01 14:03 UTC, atlamax commented on src/lesson_2/main_tasks/Task07.java
> +        System.out.println((radius*2) >= Math.sqrt((sideA*sideA) + (sideB*sideB)) ? "The circle WILL fully cover the rectangle."
This logic is not readable and hard to understand. It would be good if you:
a) Create separate boolean variable and assign value to it. Good boolean variable names starts from "is", "can", "has".
b) Create method that will return boolean value

For example:
boolean canCover = ....
System.out.println(canCover ? "Yes" : "No")

2021-03-01 14:13 UTC, atlamax commented on src/lesson_2/main_tasks/Task09.java
> +        }
Your code can be simplified.
* Variable **result** used only in **else** block. So you have 2 options:
a) return **result** in **if** block
b) declare **result** variable only in **else** block

I didn't test, but i think that if you leave just:
int result = 1;
for (int i = 2; i <= number; i++) {
      result *= i;
}
return result;

it will return same result.

2021-03-01 14:16 UTC, atlamax commented on src/lesson_2/main_tasks/Task11.java
> +        for (int i = 2; i <= number; i++) {
Should we make **number** iterations, or can exit from loop when count >=2 ?

2021-03-01 14:20 UTC, atlamax commented on src/lesson_2/main_tasks/Task10.java
> +        long result = 1;
Same as for Task 9

2021-03-01 15:34 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task07.java
> +        System.out.println((radius*2) >= Math.sqrt((sideA*sideA) + (sideB*sideB)) ? "The circle WILL fully cover the rectangle."
Done!

2021-03-01 15:35 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task09.java
> +        }
Yes it works pretty well. Amended and tested.

2021-03-01 15:35 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task10.java
> +        long result = 1;
Done!

2021-03-01 15:36 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task11.java
> +        for (int i = 2; i <= number; i++) {
I introduced the loop break condition to stop iterations after the desired condition is checked.

2021-03-01 15:43 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task07.java
> +        System.out.println((radius*2) >= Math.sqrt((sideA*sideA) + (sideB*sideB)) ? "The circle WILL fully cover the rectangle."
Done!

2021-03-01 15:44 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task09.java
> +        }
Yes, it works pretty well. Changed and tested.

2021-03-01 15:44 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task11.java
> +        for (int i = 2; i <= number; i++) {
Introduced the loop break condition when the desired condition is checked.

2021-03-01 15:44 UTC, EvgGit82 commented
Done.

2021-03-01 15:45 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task10.java
> +        long result = 1;
Done!

2021-03-04 15:33 UTC, atlamax commented on src/lesson_2/main_tasks/Task06.java
> +        System.out.println("Is it a three-digit number? " + ((randomNumber > 99 && randomNumber < 1000) ? "Yes" : "No"));
Try with -123

2021-03-04 15:33 UTC, atlamax commented on src/lesson_2/main_tasks/Task06.java
> +        System.out.println("Is it a three-digit number? " + ((randomNumber > 99 && randomNumber < 1000) ? "Yes" : "No"));
it's a 3-digit number

2021-03-04 15:39 UTC, atlamax commented on src/lesson_2/main_tasks/Task11.java
> +    public static String isNumberPrime(int number) {
It's better to return boolen value from this function.

2021-03-04 15:40 UTC, atlamax commented on src/lesson_2/main_tasks/Task12.java
> +        for (int i =1; counter < n; i++) {
1) Start from i  = 3
2) Increase i by 3, not by 1 after each loop

2021-03-04 15:42 UTC, atlamax commented on src/lesson_2/main_tasks/Task13.java
> +        for (int randomNumber : randomNumbers) {
Everything is good, but in forst cycle you will compare number with itself. Start for-loop from 2nd element

2021-03-04 15:47 UTC, atlamax commented on src/lesson_2/main_tasks/Task16.java
> +        if (indexMin < indexMax) {
IF and ELSE block have same code.
Create 2 variables:
firstNumberIndex, secondNumberIndex
And set their values based on indexMin and indexMax.
And use block like
for (int i = firstNumberIndex+1; i < secondNumberIndex; i++) {
...
}

2021-03-04 15:56 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask01.java
> +        ArrayList<Integer> tempDigits = new ArrayList<>();
Dont' need array here, it's not optimal choise. For this task, at least.
Use counter, or int -> Srtring and get its length

2021-03-04 15:58 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask05.java
> +        int zeroCount = 0;
Zero it's positive number. As I remember

2021-03-04 16:03 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask09.java
> +        System.out.println("After " + hours + " hours the number of amoeba will make "
Please print number of amoebs after:
* 3 hours
* 6 hours
...
* 24 hours

2021-03-04 16:06 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask12.java
> +            System.out.println(inch + " inch(s) = " + (inch*2.54) + " cm.");
2.54 - this is "magic number". Create private variable on class level, because this is constant

2021-03-04 16:07 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask13.java
> +        for (int i = 2; i < 101; i++) {
Simply increase i + 2 in the end of loop and you'll not need if-block

2021-03-04 16:07 UTC, atlamax commented on src/lesson_2/optional_tasks/OptTask14.java
> +        for (int i = 1; i < 100; i++) {
The same here

2021-03-04 16:09 UTC, atlamax commented
@EvgGit82 
I finish with review. Please review, change where require. And please, push all changes by 1 single commit.
Good luck!

2021-03-04 16:48 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask05.java
> +        int zeroCount = 0;
"Because zero is neither positive nor negative, the term nonnegative is sometimes used to refer to a number that is either positive or zero, while nonpositive is used to refer to a number that is either negative or zero. Zero is a neutral number." (Wiki)

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task06.java
> +        System.out.println("Is it a three-digit number? " + ((randomNumber > 99 && randomNumber < 1000) ? "Yes" : "No"));
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task11.java
> +    public static String isNumberPrime(int number) {
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task12.java
> +        for (int i =1; counter < n; i++) {
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task13.java
> +        for (int randomNumber : randomNumbers) {
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/main_tasks/Task16.java
> +        if (indexMin < indexMax) {
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask01.java
> +        ArrayList<Integer> tempDigits = new ArrayList<>();
Done

2021-03-04 16:55 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask09.java
> +        System.out.println("After " + hours + " hours the number of amoeba will make "
Done

2021-03-04 17:00 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask12.java
> +            System.out.println(inch + " inch(s) = " + (inch*2.54) + " cm.");
Done

2021-03-04 17:01 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask13.java
> +        for (int i = 2; i < 101; i++) {
Done

2021-03-04 17:02 UTC, EvgGit82 commented on src/lesson_2/optional_tasks/OptTask14.java
> +        for (int i = 1; i < 100; i++) {
Done

2021-03-29 16:28 UTC, michaelkotor requested changes

2021-03-29 16:28 UTC, michaelkotor commented on src/lesson_2/main_tasks/Task16.java
> +        int[] randomNumbers = new int[10];
а можно вынести в отдельную функцию? не очень понятно, где тест, а сама реализация

2021-03-29 16:28 UTC, michaelkotor commented on src/lesson_2/main_tasks/Task17.java
> +        int arraySize = (int) (5+Math.random()*16);
какой тут диапозон?

2021-03-29 16:28 UTC, michaelkotor commented on src/lesson_2/main_tasks/Task17.java
> +    public static void showArray (int [][] array ) {
если можно нужную функцию вот так, иначе очень сложно понять

2021-03-29 18:00 UTC, EvgeniyTsarkov commented on src/lesson_2/main_tasks/Task16.java
> +        int[] randomNumbers = new int[10];
Done. Refactored and tested.

2021-03-29 18:01 UTC, EvgeniyTsarkov commented on src/lesson_2/main_tasks/Task17.java
> +        int arraySize = (int) (5+Math.random()*16);
There was no specific range set. We were requested to makee it random. 
But okay, lets make it random in the range from 5 to 50.

2021-03-29 18:01 UTC, EvgeniyTsarkov commented on src/lesson_2/main_tasks/Task17.java
> +    public static void showArray (int [][] array ) {
Done. Refactored and tested.

2021-03-30 15:12 UTC, michaelkotor approved these changes

2021-03-30 15:20 UTC, merged