Lesson 5
EvgeniyTsarkov/FreeIT-Java pull request #9
Opened 2021-03-20 19:09 UTC by EvgGit82

The following tasks have been uploaded:
- Main tasks: 25-27
- Additional tasks: "Computer"
- Abstract classes tasks: "Transport"
- Interface tasks: "Robot", "Clothing", "Spaceport"
Please check!

2021-03-27 23:08 UTC, michaelkotor commented
69 файлов?)

2021-03-27 23:41 UTC, EvgeniyTsarkov commented
> 69 файлов?)

Да, такие у нас домашки.

2021-03-28 14:28 UTC, michaelkotor requested changes

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/abstractstasks/transport/abstracts/AirTransport.java
> +    public String toString() {
если используешь lombok, то он умеет в этот метод

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/additionaltasks/computer/commands/GetNumberFromScanner.java
> +        int number = -1;
можно без number, просто return

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/additionaltasks/computer/commands/ShowMenu.java
> +    Computer computer;
модификаторы?

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/additionaltasks/computer/commands/ShowMenu.java
> +            option = new GetNumberFromScanner().Execute();
метод с маленькой буквы

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/interfacetasks/robot/hands/SamsungHand.java
> +    public String toString() {
Data включает в себя этот метод с похожей реализацией

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/interfacetasks/robot/hands/SonyHand.java
> +    public int getPrice() {
геттер тоже сгенерируется, даже если он нужен для интерфейса

2021-03-28 14:28 UTC, michaelkotor commented on src/lesson_5/com/interfacetasks/spaceport/SpacePortRunner.java
> +        new FillSpaceshipsList(spaceshipsList).Execute();
имена функций с маленькой буквы, это не С#)

2021-03-28 15:04 UTC, EvgeniyTsarkov commented on src/lesson_5/com/abstractstasks/transport/abstracts/AirTransport.java
> +    public String toString() {
Resolved in Telegram discussion.

2021-03-28 15:04 UTC, EvgeniyTsarkov commented on src/lesson_5/com/additionaltasks/computer/commands/GetNumberFromScanner.java
> +        int number = -1;
Done! Learned a lot from this.

2021-03-28 15:04 UTC, EvgeniyTsarkov commented on src/lesson_5/com/additionaltasks/computer/commands/ShowMenu.java
> +    Computer computer;
Done. Now "private"

2021-03-28 15:04 UTC, EvgeniyTsarkov commented on src/lesson_5/com/additionaltasks/computer/commands/ShowMenu.java
> +            option = new GetNumberFromScanner().Execute();
Done!

2021-03-28 15:05 UTC, EvgeniyTsarkov commented on src/lesson_5/com/interfacetasks/robot/hands/SamsungHand.java
> +    public String toString() {
Resolved in Telegram conversation.

2021-03-28 15:05 UTC, EvgeniyTsarkov commented on src/lesson_5/com/interfacetasks/robot/hands/SonyHand.java
> +    public int getPrice() {
Done! Removed for every similar class and checked for in every project.

2021-03-28 15:06 UTC, EvgeniyTsarkov commented on src/lesson_5/com/interfacetasks/spaceport/SpacePortRunner.java
> +        new FillSpaceshipsList(spaceshipsList).Execute();
Done. Correct I watched videos on patterns where the lecturer used c# :)

2021-03-29 16:32 UTC, michaelkotor approved these changes

2021-03-29 16:39 UTC, merged